name: Mobile Automation Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  android-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install
          npm install appium-chromedriver@5.6.77

      - name: Start Appium server
        run: |
          npm install -g appium
          appium &

      - name: Run WebDriverIO tests
        run: |
          # Применим пути к файлам для Windows
          cp app/chromedriver.exe /usr/local/bin/chromedriver
          cp app/android.wdio.native.app.v1.0.8.apk /tmp/android.wdio.native.app.v1.0.8.apk
          
          # Запуск тестов
          npx wdio run wdio.conf.js
        env:
          APP_PATH: /tmp/android.wdio.native.app.v1.0.8.apk
          CHROMEDRIVER_PATH: /usr/local/bin/chromedriver
