name: Android Tests CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Android SDK Platform-Tools
        run: |
            sudo apt-get update
            sudo apt-get install -y android-sdk-platform-tools

      - name: Add Android SDK to PATH
        run: echo 'export PATH=$PATH:$ANDROID_HOME/platform-tools' >> $GITHUB_ENV

      - name: Verify ADB Installation
        run: adb version
      
      - name: Clear SDK Cache
        run: rm -rf $ANDROID_HOME/.android $ANDROID_HOME/.cache $ANDROID_HOME/.config
      
      - name: Install Android SDK Components
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-30" "build-tools;35.0.0" "system-images;android-30;google_apis_playstore;x86_64" emulator
      
      - name: Limit CPU usage
        run: echo "2" | sudo tee /proc/sys/kernel/sched_child_runs_first
      
      - name: Run Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis_playstore
          arch: x86_64
          emulator-options: -no-window -no-audio -no-boot-anim
          cores: 2
          avd-name: test
          force-avd-creation: true
          emulator-boot-timeout: 600
          emulator-port: 5554
          disable-animations: true
          disable-spellchecker: false
          disable-linux-hw-accel: auto
          enable-hw-keyboard: false
          channel: 3
          script: adb devices
      
          
      - name: Install Android SDK
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis_playstore
          arch: x86_64
          emulator-options: "-no-window -no-audio -no-boot-anim"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget curl unzip
          npm install -g appium
          npm install

      - name: Start Appium Server
        run: |
          appium --log-level error &
          sleep 10

      - name: Run WebDriverIO Tests
        run: |
          npx wdio run wdio.conf.js

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ./results
