name: Android Tests CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Android SDK Platform-Tools
        run: |
            sudo apt-get update
            sudo apt-get install -y android-sdk-platform-tools

      - name: Add Android SDK to PATH
        run: echo 'export PATH=$PATH:$ANDROID_HOME/platform-tools' >> $GITHUB_ENV

      - name: Verify ADB Installation
        run: adb version
      
          
      - name: Install Android SDK
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis_playstore
          arch: x86_64
          emulator-options: "-no-window -no-audio -no-boot-anim"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget curl unzip
          npm install -g appium
          npm install

      - name: Start Appium Server
        run: |
          appium --log-level error &
          sleep 10

      - name: Run WebDriverIO Tests
        run: |
          npx wdio run wdio.conf.js

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ./results
