name: Mobile Automation Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  android-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install

      - name: Install Android SDK and dependencies
        run: |
          # Установим Android SDK и необходимые компоненты
          sudo apt update
          sudo apt install -y wget unzip
          wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip
          unzip commandlinetools-linux-7583922_latest.zip
          sudo mv cmdline-tools /usr/local/android-sdk/
          echo "export ANDROID_HOME=/usr/local/android-sdk" >> $GITHUB_ENV
          echo "export PATH=$ANDROID_HOME/platform-tools:$ANDROID_HOME/cmdline-tools/latest/bin:$PATH" >> $GITHUB_ENV
          # Установим необходимые пакеты для работы с adb
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-29" "build-tools;30.0.3" "emulator"

      - name: Start Appium server
        run: |
          npm install -g appium
          appium &

      - name: Run WebDriverIO tests
        run: |
          # Применим пути к файлам для Windows
          cp app/chromedriver.exe /usr/local/bin/chromedriver
          cp app/android.wdio.native.app.v1.0.8.apk /tmp/android.wdio.native.app.v1.0.8.apk
          
          # Запуск тестов
          npx wdio run wdio.conf.js
        env:
          APP_PATH: /tmp/android.wdio.native.app.v1.0.8.apk
          CHROMEDRIVER_PATH: /usr/local/bin/chromedriver
